modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/soupCodez/TheLostStones/issues"

[[mods]]
modId = "theloststones"
version = "${version}"
displayName = "TheLostStones"
authors = "Soupp"
description = '''
Infintity Stones for Minecraft 1.19+!
'''
itemIcon = "minecraft:totem_of_undying"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/theloststones"

[[dependencies.theloststones]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theloststones]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theloststones]]
modId = "palladium"
mandatory = true
versionRange = "[4.0.0,)"
ordering = "AFTER"
side = "BOTH"
